'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
const categories=['general','academic','admission','registration','results','complaint','permission','absence','disciplinary','clearance','siwes','project','recommendation','student-life','fees','examination','records']
const fieldNames=['name','matric_number','department','faculty','level','institution','date','subject','recipient_title','request','reason','supporting_information']
const blank={name:'',slug:'',category:'general',description:'',required:'name,matric_number,department,faculty,level,institution,date,request',optional:'reason,supporting_information',body:'{{date}}\n\n{{recipient_title}}\n{{institution}}\n\nDear Sir/Ma,\n\n{{subject}}\n\nI, {{name}}, matriculation number {{matric_number}}, respectfully write regarding:\n\n{{request}}\n\n{{supporting_information}}\n\nYours faithfully,\n{{name}}\n{{matric_number}}'}
export default function TemplateManager(){const db=createClient();const [templates,setTemplates]=useState<any[]>([]);const [editing,setEditing]=useState<any|null>(null);const [form,setForm]=useState(blank);const [msg,setMsg]=useState('');
 async function load(){const {data,error}=await db.from('letter_templates').select('*').order('category').order('name');if(error)setMsg(error.message);setTemplates(data||[])}useEffect(()=>{load()},[])
 function edit(t:any){setEditing(t);setForm({name:t.name,slug:t.slug,category:t.category,description:t.description||'',required:(t.required_fields||[]).join(','),optional:(t.optional_fields||[]).join(','),body:t.body_template})}
 function reset(){setEditing(null);setForm(blank)}
 async function save(e:React.FormEvent){e.preventDefault();const slug=form.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const payload={name:form.name.trim(),slug,category:form.category,description:form.description.trim()||null,required_fields:form.required.split(',').map(x=>x.trim()).filter(Boolean),optional_fields:form.optional.split(',').map(x=>x.trim()).filter(Boolean),body_template:form.body.trim(),updated_at:new Date().toISOString(),version:editing?.version||'1.0',is_active:true};if(!payload.name||!payload.body_template){setMsg('Name and letter body are required.');return}const q=editing?db.from('letter_templates').update(payload).eq('id',editing.id):db.from('letter_templates').insert(payload);const {error}=await q;setMsg(error?error.message:(editing?'Template updated.':'Template added.'));if(!error){reset();load()}}
 async function toggle(t:any){const {error}=await db.from('letter_templates').update({is_active:!t.is_active,updated_at:new Date().toISOString()}).eq('id',t.id);if(error)setMsg(error.message);else load()}
 return <div><div className="page-head"><div><div className="eyebrow">ADMIN · WRITE IT</div><h1>Templates</h1></div><button className="btn btn-primary" onClick={reset}>New template</button></div><div className="grid grid-2"><form className="service-card-container form" onSubmit={save}><div className="page-head"><h2 style={{margin:0}}>{editing?'Edit template':'Add template'}</h2></div><div className="field"><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="grid grid-2"><div className="field"><label>Slug</label><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div><div className="field"><label>Category</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="field"><label>Description</label><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="field"><label>Required fields</label><input value={form.required} onChange={e=>setForm({...form,required:e.target.value})}/></div><div className="field"><label>Optional fields</label><input value={form.optional} onChange={e=>setForm({...form,optional:e.target.value})}/></div><div className="field"><label>Letter body</label><textarea rows={18} required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><div className="notice"><strong>Variables:</strong> {fieldNames.map(f=>`{{${f}}}`).join(' · ')}</div>{msg&&<div className="badge">{msg}</div>}<div className="actions"><button className="btn btn-primary">{editing?'Save changes':'Add template'}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={reset}>Cancel</button>}</div></form><div className="service-card-container"><div className="page-head"><h2 style={{margin:0}}>Library</h2><span className="badge">{templates.length}</span></div><div className="list">{templates.map(t=><div className="list-item" key={t.id}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{t.name}</strong><span className={`badge ${t.is_active?'good':'bad'}`}>{t.is_active?'LIVE':'OFF'}</span></div><div className="muted" style={{fontSize:12,marginTop:4}}>{t.category} · v{t.version}</div><div className="actions" style={{marginTop:8}}><button className="btn btn-secondary" onClick={()=>edit(t)}>Edit</button><button className="btn btn-ghost" onClick={()=>toggle(t)}>{t.is_active?'Disable':'Enable'}</button></div></div>)}</div></div></div></div>}
