'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
const blank={title:'',summary:'',body:'',category:'admission',priority:'general',source_url:'',verification_status:'pending',published_at:''}
export default function AdminAnnouncements(){const db=createClient();const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState(blank);const [msg,setMsg]=useState('');
 async function load(){const {data}=await db.from('edureach_announcements').select('*').order('created_at',{ascending:false}).limit(50);setRows(data||[])}useEffect(()=>{load()},[])
 async function save(e:React.FormEvent){e.preventDefault();setMsg('');const {data:{user}}=await db.auth.getUser();const payload={title:form.title.trim(),summary:form.summary.trim()||null,body:form.body.trim(),category:form.category,priority:form.priority,source_url:form.source_url.trim()||null,verification_status:form.verification_status,published_at:form.published_at?new Date(form.published_at).toISOString():null,last_verified_at:form.verification_status==='verified'?new Date().toISOString():null,created_by:user?.id,updated_by:user?.id};const {error}=await db.from('edureach_announcements').insert(payload);setMsg(error?error.message:'Notice saved.');if(!error){setForm(blank);load()}}
 async function updateStatus(id:string,status:string){const payload:any={verification_status:status,updated_at:new Date().toISOString()};if(status==='verified')payload.last_verified_at=new Date().toISOString();const {error}=await db.from('edureach_announcements').update(payload).eq('id',id);if(error)setMsg(error.message);else load()}
 return <div><div className="page-head"><div><div className="eyebrow">ADMIN · UPDATES</div><h1>School notices</h1></div></div><div className="grid grid-2"><form className="service-card-container form" onSubmit={save}><h2 style={{margin:0}}>Add notice</h2><div className="field"><label>Title</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field"><label>Summary</label><input value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></div><div className="field"><label>Body</label><textarea rows={10} required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><div className="grid grid-2"><div className="field"><label>Category</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>admission</option><option>registration</option><option>examination</option><option>fees</option><option>siwes</option><option>clearance</option><option>general</option></select></div><div className="field"><label>Priority</label><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>general</option><option>important</option><option>urgent</option></select></div></div><div className="field"><label>Source URL</label><input type="url" value={form.source_url} onChange={e=>setForm({...form,source_url:e.target.value})}/></div><div className="grid grid-2"><div className="field"><label>Verification</label><select value={form.verification_status} onChange={e=>setForm({...form,verification_status:e.target.value})}><option>pending</option><option>under_review</option><option>verified</option></select></div><div className="field"><label>Publish date</label><input type="datetime-local" value={form.published_at} onChange={e=>setForm({...form,published_at:e.target.value})}/></div></div>{msg&&<div className="badge">{msg}</div>}<button className="btn btn-primary">Save notice</button></form><div className="service-card-container"><div className="page-head"><h2 style={{margin:0}}>Existing notices</h2><span className="badge">{rows.length}</span></div><div className="list">{rows.map(r=><div className="list-item" key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{r.title}</strong><span className={`badge ${r.verification_status==='verified'?'good':r.verification_status==='pending'?'warn':'bad'}`}>{r.verification_status}</span></div><div className="muted" style={{fontSize:12,marginTop:5}}>{r.category} · {r.priority}</div><div className="actions" style={{marginTop:8}}><button className="btn btn-secondary" onClick={()=>updateStatus(r.id,'under_review')}>Review</button><button className="btn btn-primary" onClick={()=>updateStatus(r.id,'verified')}>Verify</button></div></div>)}</div></div></div></div>}
