'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
export default function VerificationPage(){const db=createClient();const [ann,setAnn]=useState<any[]>([]);const [res,setRes]=useState<any[]>([]);const [msg,setMsg]=useState('');
 async function load(){const [{data:a},{data:r}]=await Promise.all([db.from('edureach_announcements').select('id,title,category,priority,verification_status,source_url').neq('verification_status','verified').order('created_at',{ascending:false}),db.from('resources').select('id,title,resource_type,status,external_url').eq('status','pending').order('created_at',{ascending:false})]);setAnn(a||[]);setRes(r||[])}useEffect(()=>{load()},[])
 async function verifyAnnouncement(id:string){const {error}=await db.from('edureach_announcements').update({verification_status:'verified',last_verified_at:new Date().toISOString()}).eq('id',id);setMsg(error?error.message:'Notice verified.');if(!error)load()}
 async function rejectAnnouncement(id:string){const {error}=await db.from('edureach_announcements').update({verification_status:'rejected',updated_at:new Date().toISOString()}).eq('id',id);setMsg(error?error.message:'Notice rejected.');if(!error)load()}
 async function resource(id:string,status:string){const {error}=await db.from('resources').update({status,updated_at:new Date().toISOString()}).eq('id',id);setMsg(error?error.message:`Resource ${status}.`);if(!error)load()}
 return <div><div className="page-head"><div><div className="eyebrow">ADMIN · TRUST</div><h1>Verification queue</h1></div></div><div className="grid grid-2"><div className="service-card-container"><div className="page-head"><h2 style={{margin:0}}>Notices</h2><span className="badge warn">{ann.length}</span></div><div className="list">{ann.length?ann.map(x=><div className="list-item" key={x.id}><strong>{x.title}</strong><div className="muted">{x.category} · {x.priority}</div><div className="muted" style={{fontSize:12,marginTop:3,overflowWrap:'anywhere'}}>{x.source_url||'No source URL recorded'}</div><div className="actions"><button className="btn btn-primary" onClick={()=>verifyAnnouncement(x.id)}>Verify</button><button className="btn btn-ghost" onClick={()=>rejectAnnouncement(x.id)}>Reject</button></div></div>):<p className="muted">No notices waiting for verification.</p>}</div></div><div className="service-card-container"><div className="page-head"><h2 style={{margin:0}}>Resources</h2><span className="badge warn">{res.length}</span></div><div className="list">{res.length?res.map(x=><div className="list-item" key={x.id}><strong>{x.title}</strong><div className="muted">{x.resource_type}</div><div className="muted" style={{fontSize:12,overflowWrap:'anywhere'}}>{x.external_url||'Uploaded file'}</div><div className="actions"><button className="btn btn-primary" onClick={()=>resource(x.id,'approved')}>Approve</button><button className="btn btn-ghost" onClick={()=>resource(x.id,'rejected')}>Reject</button></div></div>):<p className="muted">No resources waiting for moderation.</p>}</div></div></div>{msg&&<div className="notice" style={{marginTop:16}}>{msg}</div>}</div>}
