'use client'
import { useMemo,useState } from 'react'
import { calculateGpa,calculateRequiredGpa,targetStatus } from '@/lib/calculations'

export default function GpaPage(){
  const [rows,setRows]=useState([{units:3,point:5},{units:3,point:4}]); const [current,setCurrent]=useState(3.05); const [completed,setCompleted]=useState(90); const [remaining,setRemaining]=useState(45); const [target,setTarget]=useState(3.5)
  const gpa=useMemo(()=>calculateGpa(rows),[rows]); const req=calculateRequiredGpa(current,completed,remaining,target); const status=req===null?null:targetStatus(req,5)
  function update(i:number,k:'units'|'point',v:number){setRows(r=>r.map((x,n)=>n===i?{...x,[k]:v}:x))}
  return <div><section className="service-card-container" style={{background:'var(--primary-navy)',color:'#fff',border:0,marginBottom:20}}><div className="eyebrow" style={{color:'#ffd2b9'}}>CALCULATE</div><h1 style={{color:'#fff',margin:'8px 0'}}>What is your GPA?</h1></section><div className="grid grid-2"><div className="service-card-container"><div className="eyebrow">SEMESTER GPA</div>{rows.map((r,i)=><div className="grid grid-2" key={i} style={{marginBottom:10}}><div className="field"><label>Credit unit</label><input type="number" min="1" value={r.units} onChange={e=>update(i,'units',Number(e.target.value))}/></div><div className="field"><label>Grade point</label><input type="number" min="0" max="5" step="0.01" value={r.point} onChange={e=>update(i,'point',Number(e.target.value))}/></div></div>)}<button className="btn btn-secondary" onClick={()=>setRows([...rows,{units:2,point:3}])}>+ Add course</button><div style={{marginTop:20,paddingTop:16,borderTop:'1px solid rgba(10,34,92,.08)'}}><div className="label">YOUR GPA</div><div style={{fontSize:46,fontWeight:900,color:'var(--primary-navy)'}}>{gpa.toFixed(2)}</div></div></div><div className="service-card-container"><div className="eyebrow">TARGET CGPA</div><div className="form"><div className="field"><label>Current CGPA</label><input type="number" step="0.01" min="0" max="5" value={current} onChange={e=>setCurrent(Number(e.target.value))}/></div><div className="grid grid-2"><div className="field"><label>Completed credits</label><input type="number" min="0" value={completed} onChange={e=>setCompleted(Number(e.target.value))}/></div><div className="field"><label>Remaining credits</label><input type="number" min="0" value={remaining} onChange={e=>setRemaining(Number(e.target.value))}/></div></div><div className="field"><label>Target CGPA</label><input type="number" step="0.01" min="0" max="5" value={target} onChange={e=>setTarget(Number(e.target.value))}/></div></div>{req!==null&&<div style={{marginTop:20,padding:18,borderRadius:12,background:'var(--bg-light-gray)'}}><div className="label">YOU NEED</div><div style={{fontSize:36,fontWeight:900,color:req<=5?'var(--primary-navy)':'var(--secondary-orange)'}}>{req.toFixed(2)}</div><span className={`badge ${status?.tone==='good'?'good':'bad'}`}>{status?.label}</span></div>}</div></div></div>}
