'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function ProfilePage(){
  const [form,setForm]=useState({full_name:'',school:'',faculty:'',department:'',level:'',session:'',matric_number:''});const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}setEmail(user.email||'');const {data}=await s.from('profiles').select('full_name,school,faculty,department,level,session,matric_number').eq('id',user.id).maybeSingle();if(data)setForm({...form,...data});setLoading(false)})()},[])
  async function save(e:React.FormEvent){e.preventDefault();setMessage('');const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from('profiles').update(form).eq('id',user.id);setMessage(error?'Could not save. Try again.':'Saved.')} 
  if(loading)return <div className="service-card-container">Loading…</div>
  return <div><section className="service-card-container" style={{background:'var(--primary-navy)',color:'#fff',border:0,marginBottom:20}}><div className="eyebrow" style={{color:'#ffd2b9'}}>MY PROFILE</div><h1 style={{color:'#fff',margin:'8px 0'}}>Student details</h1></section><div className="grid grid-2"><form className="service-card-container form" onSubmit={save}><div className="eyebrow">STUDENT INFORMATION</div><div className="field"><label>Full name</label><input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></div><div className="field"><label>Email</label><input value={email} disabled/></div><div className="field"><label>School</label><input value={form.school} onChange={e=>setForm({...form,school:e.target.value})} placeholder="University of Calabar"/></div><div className="grid grid-2"><div className="field"><label>Faculty</label><input value={form.faculty} onChange={e=>setForm({...form,faculty:e.target.value})}/></div><div className="field"><label>Department</label><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div><div className="field"><label>Level</label><input value={form.level} onChange={e=>setForm({...form,level:e.target.value})} placeholder="300"/></div><div className="field"><label>Session</label><input value={form.session} onChange={e=>setForm({...form,session:e.target.value})} placeholder="2025/2026"/></div></div><div className="field"><label>Matric No. (optional)</label><input value={form.matric_number} onChange={e=>setForm({...form,matric_number:e.target.value})}/></div>{message&&<div className="notice">{message}</div>}<button className="btn btn-primary">Save</button></form><div className="service-card-container"><div className="eyebrow">PERSONALIZATION</div><h2 style={{color:'var(--primary-navy)',fontSize:22}}>Your school. Your information first.</h2><div className="list"><div className="list-item"><strong>My School</strong><div className="muted">Prioritise your institution and programme.</div></div><div className="list-item"><strong>Ask</strong><div className="muted">Prefer school-specific answers when available.</div></div><div className="list-item"><strong>Search</strong><div className="muted">Put your institution and department results first.</div></div></div><div className="notice" style={{marginTop:14}}><strong>Private:</strong><div className="muted" style={{marginTop:4}}>Profile details stay in your account and are not public search data.</div></div></div></div></div>
}