'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function ProfilePage(){
  const [form,setForm]=useState({full_name:'',school:'',level:'',department:''});const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}setEmail(user.email||'');const {data}=await s.from('profiles').select('full_name,school,level,department').eq('id',user.id).maybeSingle();if(data)setForm({full_name:data.full_name||'',school:data.school||'',level:data.level||'',department:data.department||''});setLoading(false)})()},[])
  async function save(e:React.FormEvent){e.preventDefault();setMessage('');const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from('profiles').update(form).eq('id',user.id);setMessage(error?'We could not save your details. Please try again.':'Your student details have been saved.')}
  if(loading)return <div className="service-card-container">Loading your student profile…</div>
  return <div>
    <section style={{background:'var(--primary-navy)',color:'#fff',borderRadius:18,padding:'30px',marginBottom:22,boxShadow:'0 12px 26px rgba(10,34,92,.12)'}}><div className="eyebrow" style={{color:'#ffd2b9'}}>MY PROFILE</div><h1 style={{color:'#fff',margin:'8px 0 10px'}}>Your student details.</h1><p style={{margin:0,color:'#e8eef9',lineHeight:1.65,maxWidth:720}}>Keep your school, level and department current so EduReach can put the right notices and tools in front of you.</p></section>
    <div className="grid grid-2"><form className="service-card-container form" onSubmit={save}><div className="eyebrow">STUDENT INFORMATION</div><div className="field"><label>Full name</label><input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="Your full name"/></div><div className="field"><label>Email address</label><input value={email} disabled/></div><div className="field"><label>University / Polytechnic / College</label><input value={form.school} onChange={e=>setForm({...form,school:e.target.value})} placeholder="University of Calabar"/></div><div className="grid grid-2"><div className="field"><label>Level</label><input value={form.level} onChange={e=>setForm({...form,level:e.target.value})} placeholder="300 Level"/></div><div className="field"><label>Department</label><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Electrical Engineering"/></div></div>{message&&<div className="notice">{message}</div>}<button className="btn btn-primary">Save student details</button></form><div className="service-card-container"><div className="eyebrow">WHAT THIS CHANGES</div><h2 style={{color:'var(--primary-navy)',fontSize:22}}>Make EduReach fit your school life.</h2><div className="list"><div className="list-item"><strong>My School</strong><div className="muted">Show information for your institution first.</div></div><div className="list-item"><strong>School notices</strong><div className="muted">Bring relevant admission, registration and academic updates forward.</div></div><div className="list-item"><strong>Academic tools</strong><div className="muted">Keep your level and department available when a tool needs context.</div></div></div><div className="notice" style={{marginTop:14,borderLeftColor:'var(--secondary-orange)'}}><strong>Privacy:</strong><div className="muted" style={{marginTop:5}}>Your student profile is private. EduReach should never expose your email, phone number, matric number or private documents through public search.</div></div></div></div>
  </div>
}
