'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function TasksPage(){
  const [tasks,setTasks]=useState<any[]>([]);const [title,setTitle]=useState('');const [due,setDue]=useState('');const [error,setError]=useState('')
  async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data}=await s.from('edureach_tasks').select('*').eq('user_id',user.id).order('due_at',{ascending:true});setTasks(data||[])}
  useEffect(()=>{load()},[])
  async function add(e:React.FormEvent){e.preventDefault();setError('');if(!title.trim()){setError('Enter what you need to do.');return}const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError('Please log in to save your tasks.');return}const {error}=await s.from('edureach_tasks').insert({user_id:user.id,title:title.trim(),due_at:due?new Date(due).toISOString():null,source_type:'manual'});if(error)setError('We could not add that task. Please try again.');else{setTitle('');setDue('');load()}}
  async function complete(id:string){const s=createClient();await s.from('edureach_tasks').update({status:'completed'}).eq('id',id);load()}
  const pending=tasks.filter(t=>t.status==='pending').length;const completed=tasks.filter(t=>t.status==='completed').length
  return <div>
    <section style={{background:'var(--primary-navy)',color:'#fff',borderRadius:18,padding:'30px',marginBottom:22,boxShadow:'0 12px 26px rgba(10,34,92,.12)'}}><div className="eyebrow" style={{color:'#ffd2b9'}}>MY SCHOOL TASKS</div><h1 style={{color:'#fff',margin:'8px 0 10px'}}>Things you cannot afford to forget.</h1><p style={{margin:0,color:'#e8eef9',lineHeight:1.65,maxWidth:720}}>Course registration, school fees, SIWES, project work, clearance and exams in one simple list.</p></section>
    <div className="grid grid-3"><div className="service-card-container"><div className="label">Still to do</div><div className="stat" style={{color:'var(--primary-navy)'}}>{pending}</div><div className="muted">Pending reminders</div></div><div className="service-card-container"><div className="label">Done</div><div className="stat" style={{color:'var(--secondary-orange)'}}>{completed}</div><div className="muted">Completed</div></div><div className="service-card-container"><div className="label">All reminders</div><div className="stat">{tasks.length}</div><div className="muted">Your current list</div></div></div>
    <section className="section" style={{paddingBottom:0}}><div className="grid grid-2"><div className="service-card-container"><div className="eyebrow">01 · ADD A REMINDER</div><h2 style={{color:'var(--primary-navy)',margin:'7px 0 16px'}}>What do you need to do?</h2><form className="form" onSubmit={add}><div className="field"><label>Task</label><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Submit SIWES form"/></div><div className="field"><label>Deadline <span className="muted">(optional)</span></label><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></div>{error&&<div className="badge bad">{error}</div>}<button className="btn btn-primary">Add reminder</button></form></div><div className="service-card-container"><div className="eyebrow">02 · YOUR SCHOOL LIST</div><h2 style={{color:'var(--primary-navy)',margin:'7px 0 16px'}}>Pending & recent</h2>{tasks.length?<div className="list">{tasks.map(t=><div className="list-item" key={t.id}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><strong>{t.title}</strong><span className={`badge ${t.status==='completed'?'good':''}`}>{t.status==='completed'?'DONE':'TO DO'}</span></div><div className="muted" style={{marginTop:5}}>{t.due_at?new Date(t.due_at).toLocaleString('en-NG'):'No deadline'}</div>{t.status==='pending'&&<button className="btn btn-secondary" style={{marginTop:9}} onClick={()=>complete(t.id)}>Mark done</button>}</div>)}</div>:<div className="notice"><strong>No reminders yet.</strong><div className="muted" style={{marginTop:4}}>Add the next school task you must remember.</div></div>}</div></div></section>
  </div>
}
